#系统端口号
server:
  port: 8088
  servlet:
    session:
      cookie:
        name: das
        http-only: true
fuzhou:
  #审批系统下载归档文件Ip
  approveIp: 192.168.1.140
  #审批系统信息回执IP
  archiveresultIp: 192.168.118.224
  #智能归档配置IP
  configIp: 192.168.1.143
  #bsp系统IP
  bspIp: 192.168.1.144
  #ofd系统Ip
  ofdIp: 192.168.1.143
  #本机Ip
  localIp: 192.168.1.141
  #云阅读端口
  ofd.viewPort: 8080
  tag:
    tagword: http://192.168.1.143:5023/aiplus/nlp/word/api/v1
    tagkwords: http://192.168.1.143:5023//aiplus/nlp/keywords/api/v1
    ip: 192.168.1.143:5023
#门户系统地址
portal:
  portalSystem: http://192.168.1.143:8086
logging:
  level:
    com.dr: debug
spring:
  elasticsearch:
    uris: http://localhost:9200

# 备份数据库配置
back:
  mysql:
    # exe位置
    commandUrl: D:\database\mysql
    # 配置文件地址
    myIniUrl: D:\database\mysql\my.ini
    #需要备份的数据库名称
    dataBaseName: juye_yitihua
    #  win文件路径
    fileUrlWin: D:\database
    #  linux文件路径
    fileUrlLinux: /data/database